swagger: '2.0'
info:
  version: '1.0.0'
  title: FROP - Services

paths:
  /users:
    post:
      summary: Adds a new user
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example:   # Sample object
                id: 10
                name: Jessica Smith
      responses:
        '200':
          description: OK

  /api/aidstations/add:
      get:
        summary: Gets Users
        responses:
          '200':
            description: OK
  